后台服务/api1/urls.py
"""
# @Time    : 2022/10/20 13:46
# @Author  : violet
# @explain : api 1 路由管理
"""

from django.urls import path
from .views import user, index
from .views import admin

urlpatterns = [
    # ================================= 前端使用的视图路由 =====================================================
    # 用户登录与注册【无需 token 权限】
    path('login/', user.LoginAPIView.as_view()),  # 登录
    path('register/', user.RegisterAPIView.as_view()),  # 注册
    path('forget/password/<int:step>/', user.ForgetPasswordAPIView.as_view()),  # 忘记密码

    # 普通用户账户安全逻辑视图【需要 token 权限】
    path('reset/password/<int:pk>/', user.ResetPasswordAPIView.as_view()),  # 重置密码
    path('reset/sq/<int:pk>/', user.ResetSQAPIView.as_view()),  # 重置密保
    path('reset/portrait/<int:pk>/', user.ResetHeadPortraitAPIView.as_view()),  # 重置用户头像
    path('user/<int:pk>/', user.UserAPIView.as_view()),  # GET:获取用户详情, PUT:更改用户信息

    # 主页相关视图【需要 token 权限】
    path('model/', index.ModelAPIView.as_view()),  # 获取所有模型数据
    path('discern/<int:pk>/', index.DiscernAPIView.as_view()),  # 识别模型
    path('record/<int:pk>/', index.RecordAPIView.as_view()),  # GET: 根据用户ID获取所有对应历史记录, DELETE: 删除对应的记录
    path('detail/', index.DetailAPIView.as_view()),

    # ================================= 后台管理系统视图路由 =====================================================
    path('admin/login/', admin.admin.login, name="login"),
    path('admin/logout/', admin.admin.logout, name='logout'),

    # 用户管理
    path('admin/user/list/', admin.user.user_list, name='user_list'),
    path('admin/user/add/', admin.user.user_add, name='user_add'),
    path('admin/user/delete/<int:pk>/', admin.user.user_delete, name='user_delete'),
    path('admin/user/update/<int:pk>/', admin.user.user_update, name='user_update'),

    # 识别类型管理
    path('admin/discern/list/', admin.discern.discern_list, name='discern_list'),
    path('admin/discern/add/', admin.discern.discern_add, name='discern_add'),
    path('admin/discern/delete/<int:pk>/', admin.discern.discern_delete, name='discern_delete'),
    path('admin/discern/update/<int:pk>/', admin.discern.discern_update, name='discern_update'),

    # 识别模型管理
    path('admin/model/list/', admin.discernModel.model_list, name='model_list'),
    path('admin/model/add/', admin.discernModel.model_add, name='model_add'),
    path('admin/model/delete/<int:pk>/', admin.discernModel.model_delete, name='model_delete'),
    path('admin/model/update/<int:pk>/', admin.discernModel.model_update, name='model_update'),

    # 识别物品详情管理
    path('admin/detail/list/', admin.detail.detail_list, name='detail_list'),
    path('admin/detail/add/', admin.detail.detail_add, name='detail_add'),
    path('admin/detail/delete/<int:pk>/', admin.detail.detail_delete, name='detail_delete'),
    path('admin/detail/update/<int:pk>/', admin.detail.detail_update, name='detail_update'),

    # 管理员管理
    path('admin/list/', admin.admin.admin_list, name='admin_list'),
    path('admin/add/', admin.admin.admin_add, name='admin_add'),
    path('admin/delete/<int:pk>/', admin.admin.admin_delete, name='admin_delete'),
    path('admin/update/<int:pk>/', admin.admin.admin_update, name='admin_update'),
]

后台服务/discernServer3/urls.py
from django.urls import path, include

urlpatterns = [
    path('api/1/', include('api1.urls'))
]

后台服务/api1/models.py
from django.db import models


# Create your models here.
# ============================================================= 用户相关 =============================================================
class User(models.Model):
    """ 普通用户 """
    gender_choices = ((0, '男'), (1, '女'))

    username = models.CharField(verbose_name='用户名', unique=True, max_length=32)
    password = models.CharField(verbose_name='密码', max_length=32)
    gender = models.SmallIntegerField(verbose_name='性别', choices=gender_choices, default=0)
    phone = models.CharField(verbose_name='电话号码', max_length=11, default='')
    email = models.EmailField(verbose_name='邮箱', default='')
    headPortrait = models.CharField(verbose_name='头像', max_length=128, default='')
    sq = models.CharField(verbose_name='密保', max_length=32, default='')
    sqKey = models.CharField(verbose_name='密保密码', max_length=32, default='')
    info = models.CharField(verbose_name='个人简介', max_length=32, default='')
    delete = models.BooleanField(verbose_name='禁用', default=False)

    def __str__(self):
        return f'<id:{self.id}, username: {self.username}>'


# ============================================================= 识别模型相关 =============================================================
class DiscernType(models.Model):
    """ 识别大类, 如: 【基本识别，动漫识别...】 """

    label = models.CharField(verbose_name='识别类别名称', max_length=32, unique=True)

    def __str__(self):
        return self.label


class DiscernModel(models.Model):
    """ 识别大类对应的具体模型, 如: 【coco2018模型...】 """
    label = models.CharField(verbose_name='具体模型名称', max_length=32, default='', unique=True)
    name = models.CharField(verbose_name='模型内部名称', max_length=32)
    discernType = models.ForeignKey(DiscernType, on_delete=models.CASCADE, default='')

    def __str__(self):
        return self.label


class Record(models.Model):
    """ 识别历史记录 """
    image = models.CharField(verbose_name='识别完毕的图像', max_length=256)
    date = models.DateField(verbose_name='识别时间')
    user = models.ForeignKey(User, verbose_name='这条记录对应的用户', on_delete=models.CASCADE, default='')
    discernType = models.ForeignKey(DiscernType, verbose_name='识别类型', on_delete=models.CASCADE)
    discernModel = models.ForeignKey(DiscernModel, verbose_name='使用的模型', on_delete=models.CASCADE)
    result = models.CharField(max_length=256, verbose_name='识别结果')  # 猫 0.99,狗 0.99,猪 0.99,


class Detail(models.Model):
    """ 识别出的物体详细信息 """
    label = models.CharField(verbose_name='识别出的物体标签', max_length=32)
    info = models.TextField(verbose_name='详细描述')

后台服务/templates/admin_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        {#  操作列表  #}
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" href="{% url 'admin_add' %}">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建管理员
            </a>

            <a class="btn btn-info" href="#">
                <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
                数据导出
            </a>
        </div>

        {# 数据列表 #}
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                识别详情列表
            </div>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>username</th>
                    <th>password</th>
                    <th>email</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for item in queryset %}
                    <tr>
                        <th>{{ item.id }}</th>
                        <td>{{ item.username }}</td>
                        <td>-----</td>
                        <td>{{ item.email }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="{% url 'admin_update' item.id %}">编辑</a>
                            <a class="btn btn-danger btn-xs" href="{% url 'admin_delete' item.id %}">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        {{ pagination }}
    </div>
{% endblock %}

后台服务/templates/detail_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        {#  操作列表  #}
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" href="{% url 'detail_add' %}">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建识别详情
            </a>

            <a class="btn btn-info" href="#">
                <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
                数据导出
            </a>
        </div>

        {# 数据列表 #}
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                识别详情列表
            </div>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>物体标签</th>
                    <th>描述</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for item in queryset %}
                    <tr>
                        <th>{{ item.id }}</th>
                        <td>{{ item.label }}</td>
                        <td><textarea class="form-control" rows="4" cols="32">{{ item.info }}</textarea></td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="{% url 'detail_update' item.id %}">编辑</a>
                            <a class="btn btn-danger btn-xs" href="{% url 'detail_delete' item.id %}">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        {{ pagination }}
    </div>
{% endblock %}

后台服务/templates/discern_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        {#  操作列表  #}
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" href="{% url 'discern_add' %}">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建识别类型
            </a>

            <a class="btn btn-info" href="#">
                <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
                数据导出
            </a>
        </div>

        {# 数据列表 #}
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                识别类型列表
            </div>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>类型</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for item in queryset %}
                    <tr>
                        <th>{{ item.id }}</th>
                        <td>{{ item.label }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="{% url 'discern_update' item.id %}">编辑</a>
                            <a class="btn btn-danger btn-xs" href="{% url 'discern_delete' item.id %}">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        {{ pagination }}
    </div>
{% endblock %}

后台服务/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>后台管理系统</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1-dist/css/bootstrap.min.css' %}">
    <style>.navbar {
        border-radius: 0;
    }</style>
    {% block css %}{% endblock %}
</head>
<body>
{# 导航 #}
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">后台数据管理</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="dropdown">
{#                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"#}
{#                       aria-expanded="false">数据管理 <span class="caret"></span></a>#}
{#                    <ul class="dropdown-menu">#}
                        <li><a href="{% url 'user_list' %}">用户管理</a></li>
                        <li><a href="{% url 'discern_list' %}">识别类型管理</a></li>
                        <li><a href="{% url 'model_list' %}">识别模型管理</a></li>
                        <li><a href="{% url 'detail_list' %}">识别物品详情管理</a></li>
                        <li><a href="{% url 'admin_list' %}">管理员管理</a></li>
{#                    </ul>#}
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {# 登录后的用户下拉列表 #}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">{{ request.user }} <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'logout' %}">登出</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

{# 内容 #}
<div>
    {% block content %}{% endblock %}
</div>
</body>
<script src="{% static 'js/jquery-3.6.1.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1-dist/js/bootstrap.min.js' %}"></script>
{% block js %}{% endblock %}
</html>

后台服务/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>登录界面</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}"/>
</head>
<body>
    
    <div class="login-box">
        <h4 style="text-align: center; margin: 15px; color: grey">登录界面</h4>
        <form class="input-box" action='{% url "login" %}' method="post">
            {% csrf_token %}
            <input type="text" placeholder="账号" id="username" name="username"/>
            <input type="password" placeholder="密码" id="password" name="password"/>
            <button>登录</button>
        </form>
        <h5 style="text-align: center; margin: 15px; color: red">{{ message }}</h5>
    </div>

</body>
</html>

后台服务/templates/model_form.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker-1.9.0/css/bootstrap-datepicker.min.css' %}">
{% endblock %}


{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{{ title }}</h3>
            </div>
            <div class="panel-body">
                <form action="{{ post_url }}" method="post" novalidate>
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">提交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}


{% block js %}
    <script src="{% static 'plugins/bootstrap-datepicker-1.9.0/js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker-1.9.0/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script>
        $(function (){
            $('#id_create_time').datepicker({
                format: 'yyyy-mm-dd',
                startDate: '0',
                language: 'zh-CN',
                autoclose: true
            })
        })
    </script>
{% endblock %}

后台服务/templates/model_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        {#  操作列表  #}
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" href="{% url 'model_add' %}">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建识别类型
            </a>

            <a class="btn btn-info" href="#">
                <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
                数据导出
            </a>
        </div>

        {# 数据列表 #}
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                模型列表
            </div>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>模型名称</th>
                    <th>内部名称</th>
                    <th>识别类型</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for item in queryset %}
                    <tr>
                        <th>{{ item.id }}</th>
                        <td>{{ item.label }}</td>
                        <td>{{ item.name }}</td>
                        <td>{{ item.discernType }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="{% url 'model_update' item.id %}">编辑</a>
                            <a class="btn btn-danger btn-xs" href="{% url 'model_delete' item.id %}">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        {{ pagination }}
    </div>
{% endblock %}

后台服务/templates/user_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        {#  操作列表  #}
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" href="{% url 'user_add' %}">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建用户
            </a>

            <a class="btn btn-info" href="#">
                <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
                数据导出
            </a>
        </div>

        {# 数据列表 #}
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                用户列表
            </div>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>用户名</th>
                    <th>密码</th>
                    <th>性别</th>
                    <th>电话</th>
                    <th>邮箱</th>
                    <th>头像</th>
                    <th>密保</th>
                    <th>答案</th>
                    <th>简介</th>
                    <th>禁用</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for item in queryset %}
                    <tr>
                        <th>{{ item.id }}</th>
                        <td>{{ item.username }}</td>
                        <td>-----</td>
                        <td>{{ item.get_gender_display }}</td>
                        <td>{{ item.phone }}</td>
                        <td>{{ item.email }}</td>
                        <td>{{ item.headPortrait }}</td>
                        <td>{{ item.sq }}</td>
                        <td>-----</td>
                        <td>{{ item.info }}</td>
                        <td>{{ item.delete }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="{% url 'user_update' item.id %}">编辑</a>
                            <a class="btn btn-danger btn-xs" href="{% url 'user_delete' item.id %}">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        {{ pagination }}
    </div>
{% endblock %}